### ISSUE TITLE
请教一下traefik + cloudreve + mysql + redis配置方案

### ISSUE THREAD

**Issue by ShangWangNUST** [expoli/docker-compose-files#11]
请问大佬你的traefik + cloudreve + mysql + redis方案有没有更详细点的配置介绍呀？我刚接触docker配置没多久，是不是docker-compose里的邮箱、域名、密码都要修改呢？还要就是注释掉的一些端口和网页面板。打扰了，谢谢。

**Comment by expoli** [comment]
很抱歉现在才看到、今天我完善了相关的文档配置

**Comment by expoli** [comment]
@ShangWangNUST cloudreve 配置一共拥有两个部分一个是 [conf.ini](https://github.com/expoli/docker-compose-files/blob/master/Cloudreve/conf.ini) 一个是 [docker-compose.yaml ](https://github.com/expoli/docker-compose-files/blob/master/Cloudreve/docker-compose.yaml) 中的 label 以及数据库部分

数据库部分的配置保证 cloudreve 与 docker-compose 中的数据库密码一致即可，redis 密码不需要额外配置

```yaml
  db:
    image: mariadb
    command: --max_allowed_packet=32505856 --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: cloudreve_db
    restart: always
    volumes:
      - /data/Cloudreve/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=cloudreve
      - MYSQL_USER=cloudreve
```
- label 中的邮箱是在SSL证书无法完成自动续签、即将过期的时候进行邮件通知的
- 域名是用来访问你的 cloudreve 的域名，需要80-443能够正常访问才能正常办法SSL证书
- 注释掉的端口是因为默认采用的是 host 网络模式，现阶段已经修改成端口映射模式，可自行选择，host模式如果开启了防火墙，需要自己手动放行相应端口（为兼容性考虑，所以默认注释掉了端口模式，可自行选择、同时也提出了默认会使用哪些端口）
邮箱
